version: '3.8'

services:
  flask_timesaver_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_timesaver_app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
      
volumes:
  mysql_data: