version: '3.8'

services:
  mysql_timesaver_db:
    image: mysql:latest
    container_name: mysql_timesaver_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask_timesaver_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_timesaver_app
    restart: always
    depends_on:
      - mysql_timesaver_db
    env_file:
      - .env
    ports:
      - "5000:5000"
      
volumes:
  mysql_data: