"""empty message

Revision ID: 4f93f918ba6f
Revises: 
Create Date: 2025-04-01 19:30:48.425291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f93f918ba6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_date', sa.Date(), nullable=False),
    sa.Column('schedule_time', sa.String(length=30), nullable=False),
    sa.Column('client', sa.String(length=150), nullable=False),
    sa.Column('tuss_code', sa.String(length=30), nullable=False),
    sa.Column('tuss_description', sa.String(length=150), nullable=False),
    sa.Column('agreement', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedules')
    # ### end Alembic commands ###
